name: fm_cms_pow_evt_net 
sigma: 0.0001
n_steps: 25
train_type: evt
flow_type: fm

num_epochs: 1
learningrate: 3e-5
opt: lion
loss_type: mse

lr_scheduler: true
use_swa: true
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
truth_binary_class: false

reduce_ds_train: 2_800_000
reduce_ds_valid: 35000
eval_num_events: 10000

entry_start_train: 0
entry_start_valid: 2_800_000
entry_start_test: 0

num_workers: 16
batchsize: 128
val_batchsize: 5000

eval_dir: /pscratch/sd/a/aelabd/parnassus/cfm/fastsim/FS_evals/
truth_path_train: /pscratch/sd/a/aelabd/parnassus/data/qcd470_ttbar_train_cms.root
truth_path_valid: /pscratch/sd/a/aelabd/parnassus/data/qcd470_ttbar_train_cms.root
truth_path_test: /pscratch/sd/a/aelabd/parnassus/data/qcd600_test_cms_100k.root

max_particles: 400
time_pow: true
use_global: true

hidden_dim: 128
global_dim: 16
n_res_blocks: 3

act: gelu

var_transform: !include var_transform_ttbar_qcd.yaml

truth_variables:
    - truth_pt
    - truth_eta
    - truth_phi
    - truth_vx
    - truth_vy
    - truth_vz
    - truth_class
    
pflow_variables:
    - pflow_pt
    - pflow_eta
    - pflow_phi
    - pflow_vx
    - pflow_vy
    - pflow_vz
    - pflow_class
