name: cfm_debug
sigma: 0.0001
n_steps: 25
train_type: particle
flow_type: rcfm
model_type: knn
use_knn: false

# num_epochs: 500
num_epochs: 1
learningrate: 3e-5
opt: lion
loss_type: mse_and_direction

lr_scheduler: true
lr_scheduler_dict:
    gamma: 0.5

use_swa: true
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
train_class: true
use_global: true
zero_neutral_vtx: true
use_scale_info: true

sin_cos: true

time_factor: 1000

reduce_ds_train: 2_800_000
reduce_ds_valid: 35000
eval_num_events: 10000

entry_start_train: 0
entry_start_valid: 2_800_000
entry_start_test: 0

num_workers: 6
batchsize: 128
val_batchsize: 1000

eval_dir: /pscratch/sd/a/aelabd/parnassus/cfm/fastsim/FS_evals/
truth_path_train: /pscratch/sd/a/aelabd/parnassus/data/qcd470_ttbar_train_cms.root
truth_path_valid: /pscratch/sd/a/aelabd/parnassus/data/qcd470_ttbar_train_cms.root
truth_path_test: /pscratch/sd/a/aelabd/parnassus/data/qcd600_test_cms_100k.root

max_particles: 400


hidden_dim: 96
global_dim: 20

act: silu
ca_type: double

num_dit_layers: 8

num_heads: 6
mha_config:
    do_qk_norm: true
    bias: false
    attn_type: torch-flex

var_transform: !include var_transform_ttbar_qcd.yaml

truth_variables:
    - truth_pt
    - truth_eta
    - truth_phi
    - truth_vx
    - truth_vy
    - truth_vz
    - truth_class

pflow_variables:
    - pflow_pt
    - pflow_eta
    - pflow_phi
    - pflow_vx
    - pflow_vy
    - pflow_vz
    - pflow_class
